config/routes.rb
Rails.application.routes.draw do


  devise_for :accounts

  root 'home#index'
  resources :dashboard, only: [:index]
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :budgets
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :account

  has_many :milestones
  has_many :features, through: :milestones
end

app/models/feature.rb
class Feature < ActiveRecord::Base

  has_many :milestones
  has_many :budgets, through: :milestones
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :budget
  belongs_to :feature
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_index_path if current_account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/home/index.html.erb
    <a name="top"></a>
    <div class="android-be-together-section mdl-typography--text-center">
      <div class="logo-font android-slogan">Te ayudamos a crear tu presupuesto</div>
      <div class="logo-font android-sub-slogan">Somos programadores sabemos que te complica hacerlo</div>

    </div>

app/views/layouts/_public_navbar.html.erb
<div class="android-header mdl-layout__header mdl-layout__header--waterfall">
  <div class="mdl-layout__header-row">
    <span class="android-title mdl-layout-title">
      Presupuestalo
    </span>
    <div class="android-header-spacer mdl-layout-spacer"></div>
    <div class="android-navigation-container">
      <nav class="android-navigation mdl-navigation">
      <%- if account_signed_in? %> 
        <%= link_to "Cerrar sesion", destroy_account_session_path, class: "mdl-navigation__link mdl-typography--text-uppercase", method: :delete %>
      <%- else %>

        <%= link_to "Iniciar Session", new_account_session_path, class: "mdl-navigation__link mdl-typography--text-uppercase" %>
        <%= link_to "Registrarse", new_account_registration_path, class: "mdl-navigation__link mdl-typography--text-uppercase" %>
      <% end %>
      </nav>
    </div>

    <%- unless account_signed_in? %>
      <button class="android-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
        <i class="material-icons">more_vert</i>
      </button>
      <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="more-button">
        <li class="mdl-menu__item">5.0 Lollipop</li>
        <li class="mdl-menu__item">5.0 Lollipop</li>
      </ul>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetByFeature</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <%= render 'layouts/public_navbar' %>
    <div class="android-content mdl-layout__content">
 
    <%= yield %>

    <footer class="android-footer mdl-mega-footer">
        <div class="mdl-mega-footer--top-section">
          <div class="mdl-mega-footer--left-section">
          </div>
        </div>

        <div class="mdl-mega-footer--middle-section">
          <p class="mdl-typography--font-light">Hecho con <i class="material-icons">favorite</i> para programadores de programadores</p>
        </div>

        <div class="mdl-mega-footer--bottom-section">
          <a class="android-link android-link-menu mdl-typography--font-light" id="developers-dropdown">
            Programadores
            <i class="material-icons">arrow_drop_up</i>
          </a>
          <ul class="mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect" for="developers-dropdown">
            <li class="mdl-menu__item">Twitter Personal</li>
            <li class="mdl-menu__item">Github Personal</li>
            <li class="mdl-menu__item">Repositorio</li>
          </ul>
          <a class="android-link mdl-typography--font-light" href="https://github.com/patojimenez">Creador</a>
        </div>

      </footer>

  </div>
</div>
   
</body>
</html>